[theme]
primaryColor = "#ff8c00"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1a1a1a"
textColor = "#f5f5f5"
font = "monospace"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 10

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[runner]
magicEnabled = false
fastReruns = true
